export const CONFIRMATION_ACTION_TYPES = {
    PUBLISH_EVENT: 'PUBLISH_EVENT',
    DELETE_COLLABORATOR: 'DELETE_COLLABORATOR',
    REACTIVATE_USER: 'REACTIVATE_USER',
    TRANSFER_TICKET: 'TRANSFER_TICKET',
    RESELL_TICKET: 'RESELL_TICKET',    
    DELETE_GROUP: 'DELETE_GROUP',    
} as const;

export type ConfirmationActionType = keyof typeof CONFIRMATION_ACTION_TYPES;